openapi: 3.0.1
info:
  title: API de consultorio
  description: API para controlar médicos e suas especialidades dentro do consultório
  version: 0.0.1
  termsOfService: https://www.google.com.br/
  contact:
    name: Suporte a Devs
    email: contato@example.com
    url: https://www.google.com.br/
  license:
    name: "Licença: GPLv3"
    url: https://www.google.com.br/
externalDocs:
  description: Documentaçao burocratica

  url: https://www.google.com.br/

# servidores
servers: 
- url: http//6096015d116f00174b29ba.mockapi.io
  description: API de testes
- url: https://www.google.com.br/
  description: API de produçao


# endpoints
paths:
  /especialidades:
    get:
      summary: Recupera todas as especialidades
      responses:
        200:
          description: Sucesso
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Especialidades"
      security: 
      - auth: []
                      
    post:
      summary: Cria nova especialidade
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                descricao:
                  type: string
      responses:
        201:
           $ref: "#/components/responses/Sucesso"
                      
  /especialidades/{id}:
    parameters:
      - name: id #deve ser igual ao definido no caminho do path {id}
        in: path
        schema: 
          type: integer
        required: true
    get:
      summary: Recupera uma entidade pelo ID
      responses:
        200:
        
          description: Sucesso
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Especialidade"
        400:
          description: Especialidade nao encontrada
          content:
            application/json:
              example: "Not Found"
              
    put:
      summary: Atualiza uma entidade pelo ID
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                descricao:
                  type: string        
      responses:
        200:
          $ref: "#/components/responses/Sucesso"
          
        404:
          description: Especialidade nao encontrada
          content:
            application/json:
              example: "Not Found"
              
    delete:
      summary: Deleta uma entidade pelo ID
      responses:
        200:
          description: Sucesso
          content:
            application/json:
              example: "OK"
        404:
          description: Especialidade nao encontrada
          content:
            application/json:
              example: "Not Found"
              
components:
  schemas:
    Especialidade: 
      type: object
      properties:
        id:
          type: integer
        descricao:
          type: string
    Especialidades:
      type: array
      items:
        $ref: "#/components/schemas/Especialidade"
        
          
  responses:
    Sucesso:
      description: Sucesso
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Especialidade"
  
  securitySchemes:
    auth:
      type: http
      scheme: bearer
      bearerFormat: JWT

              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              